default:
  callback: "on_select"
  uri:
    $ref: ""
  delay: 300
  payload:
    $ref: "./default/template/error.yaml"

#v 2.0.0
personal-loan-form1_2_0_0:
  condition:
    operation:
      type: AND
      input:
        value:
          - operation:
              type: EQUAL
              title: Check search message code
              input:
                value:
                  - operation:
                      type: READ
                      input:
                        value: "req_body.message.order.items.0.id"
                  - "ITEM_ID_1_PERSONAL-LOAN"
          - operation:
              type: EQUAL
              title: Check search message code
              input:
                value:
                  - operation:
                      type: READ
                      input:
                        value: "req_body.message.order.items.0.xinput.form_response.submission_id"
                  - "96814d81-7317-483c-8b87-f3aeb1d92299"
          - operation:
              type: EQUAL
              title: Check search message code
              input:
                value:
                  - operation:
                      type: READ
                      input:
                        value: "req_body.message.order.items.0.xinput.form_response.status"
                  - "SUCCESS"
          - operation:
              type: EQUAL
              title: Check search message code
              input:
                value:
                  - operation:
                      type: READ
                      input:
                        value: "req_body.context.version"
                  - "2.0.0"
  callback: "on_select"
  uri:
    $ref: ""
  delay: 300
  payload:
    $ref: "./loan/personal-loan_2_0_0/template/on_select_form1.yaml"

personal-loan-form2_2_0_0:
  condition:
    operation:
      type: AND
      input:
        value:
          - operation:
              type: EQUAL
              title: Check search message code
              input:
                value:
                  - operation:
                      type: READ
                      input:
                        value: "req_body.message.order.items.0.id"
                  - "ITEM_ID_1_PERSONAL-LOAN"
          - operation:
              type: EQUAL
              title: Check search message code
              input:
                value:
                  - operation:
                      type: READ
                      input:
                        value: "req_body.message.order.items.0.xinput.form_response.submission_id"
                  - "96814d81-7317-483c-8b87-f3aeb1d92299"
          - operation:
              type: EQUAL
              title: Check search message code
              input:
                value:
                  - operation:
                      type: READ
                      input:
                        value: "req_body.context.version"
                  - "2.0.0"
  callback: "on_select"
  uri:
    $ref: ""
  delay: 300
  payload:
    $ref: "./loan/personal-loan_2_0_0/template/on_select_form2.yaml"

personal-loan-form3_2_0_0:
  condition:
    operation:
      type: AND
      input:
        value:
          - operation:
              type: EQUAL
              title: Check search message code
              input:
                value:
                  - operation:
                      type: READ
                      input:
                        value: "req_body.message.order.items.0.id"
                  - "ITEM_ID_1_PERSONAL-LOAN"
          - operation:
              type: EQUAL
              title: Check search message code
              input:
                value:
                  - operation:
                      type: READ
                      input:
                        value: "req_body.message.order.items.0.xinput.form_response.submission_id"
                  - "form2_submissionid"
          - operation:
              type: EQUAL
              title: Check search message code
              input:
                value:
                  - operation:
                      type: READ
                      input:
                        value: "req_body.context.version"
                  - "2.0.0"
  callback: "on_select"
  uri:
    $ref: ""
  delay: 300
  payload:
    $ref: "./loan/personal-loan_2_0_0/template/on_select_form3.yaml"
